### PR TITLE
Assume capi-cluster namespace for Cluster API resources

### PR DESCRIPTION
**Pull request by anders-elastisys**
Since CAPI resources are created in the `capi-cluster` namespace by default, this PR adds so that the aliases assumes this namespace for CAPI resources.

### CODE REVIEW

**Review by Elias-elastisys — APPROVED** [review]

**Review by william-elastisys — APPROVED** [review]
Är den incompatible med `n` positional_arg? Eller kan man ha flera -n?

**Comment by anders-elastisys** [comment]
Ja, den overridear om du speccar `n`
image

**Comment by Carl-Elastisys** [comment]
Yes for us at Elastisys it would be true that these components are always in capi-cluster namespace but if you are using Tanzu it would not be true, but that is fine since I don't use it that much.

An improvement could be creating some parameter that could toggle or change this default namespace for capi commands.

**Comment by anders-elastisys** [comment]
@Carl-Elastisys ye, I guess this is a bit "Elastisys" specific alias, but since you can override it still I would say it is fine. Your improvement is valid but I am not going to spend time on that :sweat_smile:

**Pull request merged**
